# Keep Flutter engine / plugin entry points
-keep class io.flutter.embedding.android.** { *; }
-keep class io.flutter.embedding.engine.deferredcomponents.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.** { *; }

# Keep Play Feature & Asset Delivery classes (new artifacts)
-keep class com.google.android.play.feature.delivery.** { *; }
-keep class com.google.android.play.assetdelivery.** { *; }
-keep class com.google.android.play.appupdate.** { *; }
-keep class com.google.android.play.review.** { *; }

# Keep android tasks and listeners used by Play libraries
-keep class com.google.android.play.core.tasks.** { *; }

# If you previously had rules generated by R8, append them here:
# (copy the contents of build/app/outputs/mapping/release/missing_rules.txt and paste them below)
# << PASTE contents of missing_rules.txt here >>

# Please add these rules to your existing keep rules in order to suppress warnings.
# This is generated automatically by the Android Gradle plugin.
-dontwarn com.google.android.play.core.tasks.OnFailureListener
-dontwarn com.google.android.play.core.tasks.OnSuccessListener
-dontwarn com.google.android.play.core.tasks.Task